export const movies = [
    {
        id: 1,
        image: 'https://i.pinimg.com/736x/34/a2/00/34a200676b1d5a1b86584cdc62047d35.jpg',
        name: "Flash Speedster Man",
        description: "The film is influenced by the comic book storyline Flashpoint (2011), featuring other DC characters, such as Calle's Supergirl and both Ben Affleck's and Keaton's versions of Batman. Principal photography took place from April to October 2021 at Warner Bros. Studios, Leavesden and on location around the United Kingdom.",
        type: 'MOVIE',
        genre: 'HORROR',
        year: '2021',
        country: 'UK',
        lang: 'ENG',
        continuous: '150 minutes',
        age: '13+',
        video: 'https://www.youtube.com/embed/XY_tkp1YiEg?si=BlLLWTV1ZMuNyRNI',
        trailer: 'https://www.youtube.com/embed/hebWYacbdvc?si=CdLnV9MSumUu3Ggm'
    },
    {
        id: 2,
        image: 'https://wallpapercave.com/wp/wp12302330.jpg',
        name: "Fast X",
        description: `Synopsis. In 2011, Dante Reyes, the son of drug lord Hernán Reyes, attempts to stop Dominic "Dom" Toretto and Brian O'Conner from stealing the vault containing the fortune of his father. However, Dom uses the vault to ram Dante's turreted SUV into the ocean, but Dante survives and swears revenge against Dom.`,
        type: 'MOVIE',
        genre: 'ACTION',
        year: '2023',
        country: 'US',
        lang: 'ENG',
        continuous: '141 minutes',
        age: '15+',
        video: 'https://www.youtube.com/embed/TTliqDRkWIE?si=Nr7lQToaDUhHnZRw',
        trailer: 'https://www.youtube.com/embed/32RAq6JzY-w?si=WanSEZ5qV69gUG8z'
    },
    {
        id: 3,
        image: 'https://cubecinema.com/media/diary/movieposter.jpeg',
        name: "Hakers",
        description: "Hackers is a 1995 American crime thriller film directed by Iain Softley and starring Jonny Lee Miller, Angelina Jolie, Jesse Bradford, Matthew Lillard, Laurence Mason, Renoly Santiago, Lorraine Bracco, and Fisher Stevens. The film follows a group of high school hackers and their involvement in an attempted theft.HACKERS (1995) The film is 'pretty realistic in terms of techniques use — except for 'the Gibson' in Hackers, but, hey, we all secretly want that to be true.",
        type: 'CARTOON',
        genre: "CYBER | ACTION",
        year: '1995',
        country: 'USA',
        lang: 'ENG',
        continuous: '107 minutes',
        age: '16+',
        video: 'https://www.youtube.com/embed/vrdmmTaA7Ec?si=O-yalhtF7VWyM1vj',
        trailer: 'https://www.youtube.com/embed/Rn2cf_wJ4f4?si=X8s30mZh1WgGGkwW'
    },
    {
        id: 4,
        image: 'https://www.ixpap.com/images/2021/11/Spider-Man-No-Way-Home-Wallpaper-15.jpg',
        name: "Spider-Man No Way Home",
        description: "Peter Parker's secret identity is revealed to the entire world. Desperate for help, Peter turns to Doctor Strange to make the world forget that he is Spider-Man. The spell goes horribly wrong and shatters the multiverse, bringing in monstrous villains that could destroy the world. The Multiverse Unleashed. Spider-Man's determination and resilience makes him an amazing superhero: despite the numerous setbacks that he is forced to face, Spider-Man never backs down from a challenge.",
        type: 'MOVIE',
        genre: 'ACTION | FANTASY | ADVENTURE',
        year: '2019',
        country: 'USA',
        lang: 'ENG',
        continuous: '181 minutes',
        age: '16+',
        video: 'https://www.youtube.com/embed/S8ZUtWTuHT4?si=oL4va0pmCHk7mypW',
        trailer : 'https://www.youtube.com/embed/JfVOs4VSpmA?si=BDJjcEYL2W1hmTHU'
    },
    {
        id: 5,
        image: 'https://w0.peakpx.com/wallpaper/862/584/HD-wallpaper-wednesday-addams-phone.jpg',
        name: "Wednesday",
        description: "The series is a detective story filled with supernatural forces. The main character of the series is Wednesday Addams, one of the members of the Addams family and the only daughter of Gomez and Morticia Addams, who becomes a student at Nevermore Academy. She is trying to master her emerging psychic abilities, stop the monstrous murders of the monster that is terrorizing the local town of Jericho, and unravel the mystery that her parents were drawn into 32 years ago - all against the backdrop of her new and very complicated relationship at the academy. ][5][6].",
        type: 'MOVIE',
        genre: "HORROR",
        year: '2022',
        country: 'USA',
        lang: 'ENG',
        continuous: '8 episodes',
        age: '14+',
        video: 'https://www.youtube.com/embed/8WpPyHJiznE?si=-yQFZFMWsSnMtJ7t',
        trailer: 'https://www.youtube.com/embed/Di310WS8zLk?si=sQPukn3mtZtibAL_'
    },
    {
        id: 6,
        image: 'https://www.sonypictures.com/sites/default/files/styles/max_560x840/public/title-key-art/cobrakai_onesheet_1400x2100_s5.jpg?itok=XbT3e0Pv',
        name: "Cobra Kai",
        description: "Barry Allen travel back in time to change the course of events that led to his mother's murder when he was a child.",
        type: 'MOVIE',
        genre: "ACTION",
        year: '2018-2023',
        country: 'US',
        lang: 'ENG',
        continuous: '6 episodes',
        age: '16+',
        video: 'https://www.youtube.com/embed/d6qv9N6iK3M?si=qY8aYZKrSND4Ul7i',
        trailer: 'https://www.youtube.com/embed/xCwwxNbtK6Y?si=eLfEDuBpm7jmD6_C'
    },
    {
        id: 7,
        image: 'https://m.media-amazon.com/images/M/MV5BNTM4NjIxNmEtYWE5NS00NDczLTkyNWQtYThhNmQyZGQzMjM0XkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_.jpg',
        name: "Black Panther 2",
        description: "A black African leopard (P. p. pardus) was sighted in the alpine zone of Mount Kenya in the winter of 1989–1990.[9] In Kenya's Laikipia County, a black leopard was photographed by a camera trap in 2007; in 2018, a female subadult black leopard was repeatedly recorded together with a spotted leopard about 50 km (31 mi) farther east in a grassland.[10]",
        type: 'MOVIE',
        genre: "ACTION FANTASY",
        year: '2018',
        country: 'USA',
        lang: 'ENG',
        continuous: '161 minutes',
        age: '11+',
        video: 'https://www.youtube.com/embed/MXJYGdZlkXU?si=eNFKT8fEYNa065OW',
        trailer: 'https://www.youtube.com/embed/xjDjIWPwcPU?si=AfIvgowTCRg5rNjF'
    },
    {
        id: 8,
        image: 'https://images.squarespace-cdn.com/content/v1/511eea22e4b06642027a9a99/1479757608621-4M9CFOJ9NEXKUHFD3GAC/Train+to+Busan.jpg',
        name: "Train to Busan",
        description: "Yeon Sang-ho’s “Train to Busan” is the most purely entertaining zombie film in some time, finding echoes of George Romero’s and Danny Boyle’s work, but delivering something unique for an era in which kindness to others seems more essential than ever. For decades, movies about the undead have essentially been built on a foundation of fear of our fellow man—your neighbor may look and sound like you, but he wants to eat your brain—but “Train to Busan” takes that a step further by building on the idea that, even in our darkest days, we need to look out for each other, and it is those who climb over the weak to save themselves who will suffer.",
        type: 'MOVIE',
        genre: "HORROR | ACTION | ADVENTURE",
        year: '2016',
        country: 'SOUTH COREA',
        lang: 'RU',
        continuous: '118 minutes',
        age: '18+',
        video: 'https://www.youtube.com/embed/FNzRlA8fqos?si=KicK4XyHNEfBa0Uk',
        trailer: 'https://www.youtube.com/embed/58r-Rq_TuEI?si=lGfUyTKg68c0DHNq'
    },
    {
        id: 9,
        image: 'https://e0.pxfuel.com/wallpapers/60/567/desktop-wallpaper-it-chapter-one-2017-movie-horror-movie-icons-horror-movie-art.jpg',
        name: "IT Chapter",
        description: "Parents need to know that Clown is a mean-spirited horror movie about a good dad who unwisely puts on a demonic clown suit for his son's birthday party and ends up trying to kill children. The character is punished for his deeds, even though he's more a victim of bad luck than anything.",
        type: 'MOVIE',
        genre: "HORROR",
        year: 2014,
        country: 'US',
        lang: 'ENG',
        continuous: '100 minutes',
        age: '18+',
        video: 'https://www.youtube.com/embed/-NA-4cwPsHE?si=YiXBr8R9bQ-mFf-i',
        trailer: 'https://www.youtube.com/embed/xKJmEC5ieOk?si=h5A5HfrY6DRO_EYd'
    },
    {
        id: 10,
        image: 'https://www.tvguide.com/a/img/catalog/provider/1/2/1-8731822523.jpg',
        name: "DIAMOND DOG CAPER",
        description: "Dog Gone, also known as Diamond Dog Caper, is a 2008 American comedy film directed by Mark Stouffer and starring Luke Benward, French Stewart, Brittany Curran, and Kevin Farley. The film revolves around a young boy who rescues and hides a golden retriever carrying a fortune in stolen diamonds from a band of thugs.",
        type: 'MOVIE',
        genre: "ADVENTURE",
        year: 2008,
        country: 'US',
        lang: 'ENG',
        continuous: '108 minutes',
        age: '10+',
        video: 'https://www.youtube.com/embed/S5QOnqgsvxc?si=Qg8M0tbmtd4D_vCB',
        trailer: 'https://www.youtube.com/embed/jv00MdCAz9g?si=GfYd4zF2hWWKBXsA'
    },
    {
        id: 11,
        image: 'https://m.media-amazon.com/images/M/MV5BYjExYTcwYmYtMWY2Zi00MGJlLTk3YjUtZTU1Zjg4MDc0Y2FjXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_.jpg',
        name: "SCREAM 4", 
        description: "The shocking reveal at the end of Scream shows that the killers are Tara's best friend Amber and Sam's boyfriend, Richie. They were both motivated to kill to continue the Stab franchise (the horror franchise within Scream replicating the film).Richie pursues Sam, who sees another hallucination of Billy, which brings her attention to Amber's abandoned knife. Embracing her paternal heritage, she uses the knife to stab Richie repeatedly and fatally slit his throat, before shooting him to ensure he is dead.",
        type: 'MOVIE',
        genre: "HORROR | SLASHER",
        year: 2011,
        country: 'USA',
        lang: 'ENG',
        continuous: '114 minutes',
        age: '18+',
        video: 'https://www.youtube.com/embed/fGtWMVKYmW0?si=28Ki4UY05KKvN4sC',
        trailer: 'https://www.youtube.com/embed/JKRtyVLWV-E?si=Q2hQHUNyQeXu9O0A'
    },
    {
        id: 12,
        image: 'https://horrorcultfilms.b-cdn.net/wp-content/uploads/2016/03/the-wrong-house.jpg',
        name: "The wrong House", 
        description: `
        As the summary says, Rebecca and Brian move into a new house in which strange things start happening from food they didn't order being delivered to their house, to exterrminators being called because of a rat problem they say they don't have. They soon learn whose behind all of these "pranks".
        `,
        type: 'MOVIE',
        genre: "HORROR",
        year: 2016,
        country: 'USA',
        lang: 'ENG',
        continuous: '100 minutes',
        age: '18+',
        video: 'https://www.youtube.com/embed/XimvdthKNas?si=qORfPrRiGKZQVOLi',
        trailer: 'https://www.youtube.com/embed/JKRtyVLWV-E?si=Q2hQHUNyQeXu9O0A'
    },
]

